-- 유저 테이블 생성
CREATE TABLE USERS(
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PW VARCHAR2(20) NOT NULL,
    USER_NM VARCHAR2(30) NOT NULL
);

ALTER TABLE USERS ADD PRIMARY KEY(USER_ID); -- PK 추가

COMMENT ON COLUMN "USERS"."USER_ID" IS '사용자 아이디';
COMMENT ON COLUMN "USERS"."USER_PW" IS '사용자 비밀번호';
COMMENT ON COLUMN "USERS"."USER_NM" IS '사용자 이름';

-- 투두 테이블 생성
CREATE TABLE TODO(
    TODO_IDX INT NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    TODO_TITLE VARCHAR2(200) NOT NULL,
    TODO_MEMO VARCHAR2(1000),
    TODO_DDLN DATE,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_TIME TIMESTAMP NOT NULL,
    DELETED_TIME TIMESTAMP NOT NULL
);

ALTER TABLE TODO ADD PRIMARY KEY(TODO_IDX); -- PK 추가

ALTER TABLE TODO ADD CONSTRAINT FK_USERID
				 FOREIGN KEY(USER_ID)
				 REFERENCES USERS(USER_ID); -- FK 추가 

CREATE SEQUENCE ECO_TODO.TODO_SEQ INCREMENT BY 1
								  START WITH 1
								  MINVALUE 1
								  MAXVALUE 9999
								  NOCYCLE
								  NOCACHE
								  ORDER; -- 투두테이블 SEQ 추가

COMMENT ON COLUMN "TODO"."TODO_IDX" IS '투두 인덱스, PK, SEQ';
COMMENT ON COLUMN "TODO"."USER_ID" IS '사용자 아이디, FK';
COMMENT ON COLUMN "TODO"."TODO_TITLE" IS '투두 제목';
COMMENT ON COLUMN "TODO"."TODO_MEMO" IS '투두 메모';
COMMENT ON COLUMN "TODO"."TODO_DDLN" IS '투두 마감일';
COMMENT ON COLUMN "TODO"."CREATED_TIME" IS '작성 일시';
COMMENT ON COLUMN "TODO"."UPDATED_TIME" IS '수정 일시';
COMMENT ON COLUMN "TODO"."DELETED_TIME" IS '삭제 일시';

-- 필터 테이블 생성
CREATE TABLE FILTERS(
    TODO_IDX INT NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    FIL_TDY CHAR(1) DEFAULT 0,
    FIL_IMP CHAR(1) DEFAULT 0,
    FIL_CMPLT CHAR(1) DEFAULT 0,
    FIL_DLT CHAR(1) DEFAULT 0
);

ALTER TABLE FILTERS ADD CONSTRAINT FK_TODOIDX
                    FOREIGN KEY(TODO_IDX)
                    REFERENCES TODO(TODO_IDX); -- FK 추가

ALTER TABLE FILTERS ADD CONSTRAINT FK_USERID_IN_FIL
                    FOREIGN KEY(USER_ID)
                    REFERENCES USERS(USER_ID); -- FK 추가
                    
-- 추가로 변경한 부분
ALTER TABLE USERS MODIFY USER_PW VARCHAR2(100);

ALTER TABLE TODO MODIFY UPDATED_TIME NULL;
ALTER TABLE TODO MODIFY DELETED_TIME NULL;

ALTER TABLE FILTERS MODIFY FIL_TDY NOT NULL;
ALTER TABLE FILTERS MODIFY FIL_IMP NOT NULL;
ALTER TABLE FILTERS MODIFY FIL_CMPLT NOT NULL;
ALTER TABLE FILTERS MODIFY FIL_DLT NOT NULL;

-- 설정 저장 테이블 생성
CREATE TABLE SETTINGS(
	USER_ID VARCHAR2(20) NOT NULL,
	NEWTODO_TOP CHAR(1) DEFAULT 0, -- 1 yes / 0 NO 새로 생기는 것 위로 
	IMPTODO_TOP CHAR(1) DEFAULT 0 -- 1 yes / 0 NO 중요한 것 위로  
	);

COMMENT ON COLUMN "SETTINGS"."USER_ID" IS '사용자 아이디, PK';
COMMENT ON COLUMN "SETTINGS"."NEWTODO_TOP" IS '새로 생성되는 것 위로 1 yes, 0 no';
COMMENT ON COLUMN "SETTINGS"."IMPTODO_TOP" IS '중요한 것 위로 1 yes, 0 no';

ALTER TABLE settings ADD PRIMARY KEY(user_id); -- pk
ALTER TABLE FILTERS FOREIGN KEY(USER_ID)


DROP TABLE settings;
---------------------------------------

ALTER TABLE users ADD NEWTODO_TOP char(1) DEFAULT 0;
ALTER TABLE users ADD IMPTODO_TOP char(1) DEFAULT 0;

SELECT * FROM users;

select * FROM V_TODO_FILTER;

UPDATE users SET newtodo_top='0' WHERE user_id='test';
UPDATE users SET imptodo_top='1' WHERE user_id='test';